# NumPy

This notebook provides a comprehensive introduction to NumPy, a powerful library for numerical computing in Python. It includes detailed explanations, code examples, tables, and exercises to help you master NumPy's core features.

## Introduction to NumPy

### What is NumPy?
NumPy (Numerical Python) is a core library for scientific computing in Python. It provides support for multi-dimensional arrays and matrices, along with efficient mathematical functions to operate on them.

### Why Use NumPy?
- **Performance**: Operations on NumPy arrays are faster than Python lists due to optimized C implementations.
- **Convenience**: Built-in functions simplify array manipulation and computation.
- **Functionality**: Supports advanced operations on multi-dimensional data.

### Installation and Import
NumPy is typically pre-installed in environments like Anaconda. If not, install it with:

```bash
pip install numpy
```

Import it in Python:


## What is an “Array”?

In computer programming, an **array** is a fundamental data structure designed for storing and retrieving data in an organized way. You can think of an array as a grid in space, where each cell holds a single piece of data, called an element. The structure of an array can vary depending on its number of dimensions, and this concept is central to how arrays are used in libraries like NumPy.

### Visualizing Arrays by Dimension

- **One-dimensional (1D) array**: Imagine a simple list of numbers. It’s like a single row of cells, where each cell contains one value. For example:

  | 0 | 1 | 2 | 3 | 4 |
  |---|---|---|---|---|
  | 1 | 2 | 3 | 4 | 5 |

  Here, the numbers 1 through 5 are stored in a straight line, accessible by their position (index).

- **Two-dimensional (2D) array**: This is like a table with rows and columns. Each cell is identified by its row and column position. For example:

  |   | 0 | 1 | 2 |
  |---|---|---|---|
  | 0 | 1 | 2 | 3 |
  | 1 | 4 | 5 | 6 |
  | 2 | 7 | 8 | 9 |

  This could represent a grid of values, such as a small spreadsheet or a matrix.

- **Three-dimensional (3D) array**: Picture a stack of tables, like pages in a book. Each "page" is a 2D array, and the third dimension adds depth. For instance, you might have multiple 2D tables stacked together, where each table is identified by its position in the stack.

In **NumPy**, this concept is taken further with the `ndarray` class, which stands for "N-dimensional array." NumPy generalizes arrays to any number of dimensions, making it possible to work with data in 1D, 2D, 3D, or even higher dimensions, depending on your needs.

### Characteristics of NumPy Arrays

NumPy arrays come with specific rules that distinguish them from more flexible data structures (like Python lists). These restrictions enable NumPy to optimize performance:

- **Uniform data type**: All elements in a NumPy array must be of the same data type (e.g., all integers or all floats). This consistency allows for efficient memory use and faster computations.
- **Fixed size**: Once a NumPy array is created, its total size cannot change. You can reshape it, but you can’t add or remove elements without creating a new array.
- **Rectangular shape**: The array must maintain a regular, grid-like structure. For example, in a 2D array, every row must have the same number of columns—no "jagged" or uneven shapes are allowed.

When these conditions are met, NumPy takes advantage of them to make arrays **faster**, **more memory-efficient**, and **more convenient** than less restrictive alternatives like Python lists. This is why NumPy is a cornerstone for numerical computing in Python.


In [ ]:
import numpy as np


### Memory Usage: Python List vs. NumPy Array

Python lists and NumPy arrays store data differently, leading to variations in memory efficiency. A Python list is a dynamic, flexible structure that stores references to objects (e.g., integers), each with additional overhead. A NumPy array, by contrast, is a contiguous block of memory with a uniform data type, reducing overhead and optimizing storage.

Let’s compare the memory usage with practical examples.

#### Example 1: Small Array/List with Integers
We’ll create a small list and a NumPy array with the same integers and measure their memory usage.



In [38]:
import sys
import numpy as np

# Create a Python list and a NumPy array with the same data
py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])



In [40]:
print("Python list:", py_list)
print("Numpy array", np_array)

Python list: [1, 2, 3, 4, 5]
Numpy array [1 2 3 4 5]


In [42]:
# Memory usage of Python list
# sys.getsizeof() gives the size of the list object itself
# Each element is a reference to an integer object, so we add the size of one integer object
list_size = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)

# Memory usage of NumPy array
# np_array.nbytes gives the size of the data buffer
# sys.getsizeof(np_array) includes the array object overhead
array_size = sys.getsizeof(np_array) + np_array.nbytes

print("Python list memory usage:", list_size, "bytes")
print("NumPy array memory usage:", array_size, "bytes")
print("Difference (List - Array):", list_size - array_size, "bytes")

Python list memory usage: 244 bytes
NumPy array memory usage: 192 bytes
Difference (List - Array): 52 bytes



**Sample Output** (actual numbers may vary slightly by system):
```
Python list memory usage: 164 bytes
NumPy array memory usage: 144 bytes
Difference (List - Array): 20 bytes
```

**Explanation**:
- **Python list**: The `sys.getsizeof(py_list)` gives the size of the list object (e.g., 56 bytes for an empty list + 8 bytes per pointer on a 64-bit system). Each integer is a separate Python object, typically 28 bytes each (on a 64-bit system), leading to significant overhead (5 * 28 = 140 bytes for the integers + 24 bytes for the list structure).
- **NumPy array**: The `nbytes` attribute reports the size of the data buffer (5 elements * 8 bytes per `int64` = 40 bytes). The array object itself has some overhead (e.g., 104 bytes), but the data is stored contiguously without per-element object overhead.

---



#### Example 2: Larger Array/List with Integers
Now, let’s scale up to 1000 elements to see the difference more clearly.

In [44]:
import sys
import numpy as np

# Create a larger Python list and NumPy array
py_list = list(range(1000))
np_array = np.arange(1000)

# Memory usage of Python list
list_size = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)

# Memory usage of NumPy array
array_size = sys.getsizeof(np_array) + np_array.nbytes

print("Python list memory usage:", list_size, "bytes")
print("NumPy array memory usage:", array_size, "bytes")
print("Difference (List - Array):", list_size - array_size, "bytes")

Python list memory usage: 36056 bytes
NumPy array memory usage: 16112 bytes
Difference (List - Array): 19944 bytes


**Sample Output**:
```
Python list memory usage: 28856 bytes
NumPy array memory usage: 8104 bytes
Difference (List - Array): 20752 bytes
```

**Explanation**:
- **Python list**: The list object itself grows slightly (e.g., 8 bytes per pointer, so 1000 * 8 = 8000 bytes for pointers + 56 bytes base size), and each integer object adds 28 bytes (1000 * 28 = 28000 bytes). Total ≈ 28,856 bytes.
- **NumPy array**: The data buffer is 1000 * 8 bytes (`int64`) = 8000 bytes, plus ~104 bytes of overhead for the array object. Total ≈ 8104 bytes.
- **Difference**: The Python list uses over 3.5 times more memory due to per-element overhead.

---

#### Example 3: Specifying NumPy Data Type
NumPy allows control over data types, which can further reduce memory usage. Let’s use a smaller data type (`int8` vs. `int64`).

In [ ]:
import sys
import numpy as np

# Create a Python list and NumPy arrays with different data types
py_list = list(range(100))
np_array_int64 = np.arange(100, dtype=np.int64)  # 8 bytes per element
np_array_int8 = np.arange(100, dtype=np.int8)    # 1 byte per element

# Memory usage
list_size = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)
array_int64_size = sys.getsizeof(np_array_int64) + np_array_int64.nbytes
array_int8_size = sys.getsizeof(np_array_int8) + np_array_int8.nbytes

print("Python list memory usage:", list_size, "bytes")
print("NumPy array (int64) memory usage:", array_int64_size, "bytes")
print("NumPy array (int8) memory usage:", array_int8_size, "bytes")


**Sample Output**:
```
Python list memory usage: 2952 bytes
NumPy array (int64) memory usage: 904 bytes
NumPy array (int8) memory usage: 204 bytes
```

**Explanation**:
- **Python list**: 100 integers * 28 bytes each + 856 bytes for the list structure ≈ 2952 bytes.
- **NumPy `int64`**: 100 * 8 bytes = 800 bytes + 104 bytes overhead ≈ 904 bytes.
- **NumPy `int8`**: 100 * 1 byte = 100 bytes + 104 bytes overhead ≈ 204 bytes.
- **Insight**: By choosing `int8` (1 byte per element) over `int64` (8 bytes), NumPy can drastically reduce memory usage when the data range fits (e.g., 0–255 for `int8`).

---


### Time Efficiency: Python List vs. NumPy Array

NumPy arrays are designed for numerical computations and leverage compiled C code under the hood, avoiding Python’s interpreter overhead. This makes operations on NumPy arrays significantly faster than equivalent operations on Python lists, especially for large datasets. Let’s explore this with practical examples.

#### Example 1: Element-wise Addition
We’ll add a constant value to each element in a Python list and a NumPy array, comparing execution times.

In [1]:
import time
import numpy as np

# Size of the dataset
n = 1000000

# Create a Python list and a NumPy array
py_list = list(range(n))
np_array = np.arange(n)

# Time Python list addition
start_time = time.time()
py_list_result = [x + 5 for x in py_list]
py_list_time = time.time() - start_time

# Time NumPy array addition
start_time = time.time()
np_array_result = np_array + 5
np_array_time = time.time() - start_time

print(f"Python list time: {py_list_time:.6f} seconds")
print(f"NumPy array time: {np_array_time:.6f} seconds")
print(f"Speedup (List / Array): {py_list_time / np_array_time:.2f}x")

Python list time: 0.078729 seconds
NumPy array time: 0.002028 seconds
Speedup (List / Array): 38.82x


**Sample Output** (times may vary by system):
```
Python list time: 0.085214 seconds
NumPy array time: 0.002013 seconds
Speedup (List / Array): 42.33x
```

**Explanation**:
- **Python list**: Uses a list comprehension, which involves a Python loop executed by the interpreter. Each addition requires object creation and memory management, adding overhead.
- **NumPy array**: Uses vectorized addition, where the operation is applied to all elements simultaneously in compiled C code. This eliminates per-element Python overhead, resulting in a massive speedup.

---


#### Example 2: Summing Elements
We’ll compute the sum of all elements in a large dataset using Python’s `sum()` and NumPy’s `np.sum()`.

```python
import time
import numpy as np

# Size of the dataset
n = 1000000

# Create a Python list and a NumPy array
py_list = list(range(n))
np_array = np.arange(n)

# Time Python list sum
start_time = time.time()
py_list_sum = sum(py_list)
py_list_time = time.time() - start_time

# Time NumPy array sum
start_time = time.time()
np_array_sum = np.sum(np_array)
np_array_time = time.time() - start_time

print(f"Python list sum time: {py_list_time:.6f} seconds")
print(f"NumPy array sum time: {np_array_time:.6f} seconds")
print(f"Speedup (List / Array): {py_list_time / np_array_time:.2f}x")
```

**Sample Output**:
```
Python list sum time: 0.018943 seconds
NumPy array sum time: 0.001002 seconds
Speedup (List / Array): 18.90x
```

**Explanation**:
- **Python list**: The `sum()` function iterates over the list in Python, performing additions one by one with interpreter overhead.
- **NumPy array**: `np.sum()` uses optimized C loops and SIMD (Single Instruction, Multiple Data) instructions when available, processing multiple elements in parallel. This results in a significant time reduction.

---


#### Example 3: Element-wise Multiplication (Large Dataset)
Let’s multiply two large arrays/lists element-wise.

```python
import time
import numpy as np

# Size of the dataset
n = 1000000

# Create two Python lists and two NumPy arrays
py_list1 = list(range(n))
py_list2 = list(range(n))
np_array1 = np.arange(n)
np_array2 = np.arange(n)

# Time Python list multiplication
start_time = time.time()
py_list_result = [a * b for a, b in zip(py_list1, py_list2)]
py_list_time = time.time() - start_time

# Time NumPy array multiplication
start_time = time.time()
np_array_result = np_array1 * np_array2
np_array_time = time.time() - start_time

print(f"Python list multiplication time: {py_list_time:.6f} seconds")
print(f"NumPy array multiplication time: {np_array_time:.6f} seconds")
print(f"Speedup (List / Array): {py_list_time / np_array_time:.2f}x")
```

**Sample Output**:
```
Python list multiplication time: 0.135421 seconds
NumPy array multiplication time: 0.002998 seconds
Speedup (List / Array): 45.17x
```

**Explanation**:
- **Python list**: The `zip()` and list comprehension create a new list by iterating over pairs of elements, with Python’s interpreter handling each multiplication individually.
- **NumPy array**: The `*` operator is vectorized, applying multiplication across all elements in a single, optimized operation. This avoids Python’s loop overhead and leverages low-level optimizations.

---

#### Example 4: Looping vs. Vectorization
Let’s compare explicit looping (common in traditional programming) with NumPy’s vectorized approach for squaring elements.

```python
import time
import numpy as np

# Size of the dataset
n = 1000000

# Create a Python list and a NumPy array
py_list = list(range(n))
np_array = np.arange(n)

# Time Python list with explicit loop
start_time = time.time()
py_list_result = []
for x in py_list:
    py_list_result.append(x * x)
py_list_time = time.time() - start_time

# Time NumPy array with vectorization
start_time = time.time()
np_array_result = np_array ** 2
np_array_time = time.time() - start_time

print(f"Python list loop time: {py_list_time:.6f} seconds")
print(f"NumPy array vectorized time: {np_array_time:.6f} seconds")
print(f"Speedup (List / Array): {py_list_time / np_array_time:.2f}x")
```

**Sample Output**:
```
Python list loop time: 0.189432 seconds
NumPy array vectorized time: 0.002503 seconds
Speedup (List / Array): 75.68x
```

**Explanation**:
- **Python list**: The explicit `for` loop iterates over each element, performing the squaring operation and appending to a new list. This involves repeated Python interpreter calls and list resizing overhead.
- **NumPy array**: The `**` operator is applied to the entire array at once in a vectorized manner, executed in compiled C code. This is dramatically faster, especially as the dataset grows.

---

## Creating NumPy Arrays

NumPy arrays can be created from Python lists, built-in functions, or random data. Below are examples and a table summarizing the methods.

### 1. From Python Lists
Convert lists to arrays using `np.array()`.

#### Example 1: 1D Array

In [48]:
#pip install numpy

import numpy as np

In [52]:
list_1d = [10, 20, 30, 40]
array_1d = np.array(list_1d)
print(list_1d)
print(array_1d)

[10, 20, 30, 40]
[10 20 30 40]


In [54]:
print(type(list_1d))
print(type(array_1d))

<class 'list'>
<class 'numpy.ndarray'>


In [58]:
my_tuple = (1, 2, 3, 4, 5)

my_np_array = np.array(my_tuple)
print(my_np_array)

[1 2 3 4 5]


#### Example 2: 2D Array

In [62]:
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)
print(list_2d)
print(array_2d)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


#### Example 3: With Specific Data Type

In [70]:
array_float = np.array([1, 2.4, 3], dtype=np.float32)
print(array_float)

[1.  2.4 3. ]


### 2. Using Built-in Functions
NumPy offers functions to create arrays with specific values or patterns.

#### Table: Array Creation Functions
| Function              | Description                            | Example Code                     | Output Example                |
|-----------------------|----------------------------------------|----------------------------------|-------------------------------|
| `np.zeros(shape)`     | Array of zeros                        | `np.zeros((2, 3))`              | `[[0. 0. 0.] [0. 0. 0.]]`    |
| `np.ones(shape)`      | Array of ones                         | `np.ones(4)`                    | `[1. 1. 1. 1.]`             |
| `np.full(shape, value)` | Array filled with a value           | `np.full((2, 2), 9)`            | `[[9 9] [9 9]]`             |
| `np.arange(start, stop, step)` | Evenly spaced values         | `np.arange(0, 10, 3)`           | `[0 3 6 9]`                 |
| `np.linspace(start, stop, num)` | `num` evenly spaced values | `np.linspace(1, 5, 5)`          | `[1. 2. 3. 4. 5.]`          |
| `np.eye(n)`           | Identity matrix (n x n)               | `np.eye(2)`                     | `[[1. 0.] [0. 1.]]`         |

In [78]:
zeros = np.zeros((3, 10))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [98]:
ones = np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


#### Example 4: Using `np.full()`

In [106]:
full_array = np.full((10, 10), 11)
print(full_array)

[[11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11 11 11]]


In [114]:
my_arr = np.arange(10, 21, 5)
print(my_arr)

[10 15 20]


In [118]:
lin_arr = np.linspace(5, 20, 5)
print(lin_arr)

[ 5.    8.75 12.5  16.25 20.  ]


In [120]:
# Identity matrix
id_matrix = np.eye(5)
print(id_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Example 5: Using `np.linspace()`

In [ ]:
linspace_array = np.linspace(0, 2, 6)
print(linspace_array)

### 3. Random Arrays
Use `np.random` for arrays with random values.

#### Table: Random Array Functions
| Function                  | Description                          | Example Code                     | Output Example (varies)      |
|---------------------------|--------------------------------------|----------------------------------|------------------------------|
| `np.random.rand(shape)`   | Uniform [0, 1)                      | `np.random.rand(2, 2)`          | `[[0.45 0.78] [0.12 0.91]]` |
| `np.random.randn(shape)`  | Standard normal (mean 0, std 1)     | `np.random.randn(3)`            | `[0.12 -1.5 0.89]`          |
| `np.random.randint(low, high, size)` | Random integers          | `np.random.randint(1, 10, (2, 3))` | `[[3 7 2] [5 9 1]]`     |
| `np.random.uniform(low, high, size)` | Uniform over [low, high) | `np.random.uniform(-2, 2, 4)`   | `[-1.5 0.3 1.8 -0.9]`       |

#### Example 6: Random Integers

In [ ]:
rand_int_array = np.random.randint(0, 100, (2, 4))
print(rand_int_array)

## Array Attributes and Methods

NumPy arrays have attributes to inspect their properties and methods to manipulate them.

### Table: Key Attributes
| Attribute | Description                  | Example Output (for `[[1, 2], [3, 4]]`) |
|-----------|------------------------------|------------------------------------------|
| `shape`   | Dimensions of the array      | `(2, 2)`                                |
| `dtype`   | Data type of elements        | `int64`                                 |
| `size`    | Total number of elements     | `4`                                     |
| `ndim`    | Number of dimensions         | `2`                                     |

#### Example 7: Inspecting Attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

### Table: Useful Methods
| Method            | Description                          | Example Code                     | Output Example            |
|-------------------|--------------------------------------|----------------------------------|---------------------------|
| `reshape(new_shape)` | Reshape array               | `np.arange(6).reshape(2, 3)`    | `[[0 1 2] [3 4 5]]`      |
| `max()`           | Maximum value                       | `np.array([1, 5, 3]).max()`     | `5`                       |
| `min()`           | Minimum value                       | `np.array([1, 5, 3]).min()`     | `1`                       |
| `np.where(condition)` | Indices where condition is true | `np.where(arr > 2)`          | `(array([1, 1, 1]), array([0, 1, 2]))` |
| `np.unique()`     | Unique elements                     | `np.unique([1, 1, 2, 2, 3])`   | `[1 2 3]`                 |

#### Example 8: Using `np.where()`

In [ ]:
arr = np.array([1, 4, 2, 5, 3])
indices = np.where(arr > 3)
print("Indices:", indices)
print("Values:", arr[indices])

#### Example 9: Using `np.unique()`

In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_vals = np.unique(arr)
print(unique_vals)

## Operations on Arrays

NumPy supports various operations, from basic arithmetic to advanced manipulations.

### Table: Basic Operations
| Operation         | Description                          | Example Code                     | Output Example            |
|-------------------|--------------------------------------|----------------------------------|---------------------------|
| Addition          | Element-wise addition               | `np.array([1, 2]) + 3`          | `[4 5]`                   |
| Subtraction       | Element-wise subtraction            | `np.array([5, 6]) - 2`          | `[3 4]`                   |
| Multiplication    | Element-wise multiplication         | `np.array([2, 3]) * 2`          | `[4 6]`                   |
| Division          | Element-wise division               | `np.array([4, 6]) / 2`          | `[2. 3.]`                 |
| Power             | Element-wise exponentiation         | `np.array([2, 3]) ** 2`         | `[4 9]`                   |

#### Example 10: Element-wise Operations

In [ ]:
arr = np.array([1, 2, 3, 4])
print("Add 5:", arr + 5)
print("Multiply by 3:", arr * 3)
print("Square:", arr ** 2)

### 1. Copying Arrays
Use `copy()` to avoid modifying the original array.

#### Example 11

In [ ]:
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
arr_copy[0] = 99
print("Original:", arr)
print("Copy:", arr_copy)

### 2. Concatenation
Combine arrays with `np.concatenate()`.

#### Example 12: 2D Concatenation

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

### 3. Splitting
Split arrays with `np.split()`.

#### Example 13

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 2)
print(split_arr)

## Indexing and Slicing

### Basic Slicing

#### Example 14

In [ ]:
arr = np.arange(10)
print("Slice [2:6]:", arr[2:6])
print("Every other element:", arr[::2])

### Advanced Indexing

#### Example 15: Boolean Indexing

In [ ]:
arr = np.array([10, 20, 15, 30, 25])
print("Values > 20:", arr[arr > 20])

#### Example 16: Multi-dimensional

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Row 1, Col 2:", arr_2d[1, 2])

## Broadcasting

Broadcasting enables operations on arrays of different shapes.

#### Example 17: Scalar Broadcasting

In [ ]:
arr = np.array([[1, 2], [3, 4]])
result = arr * 10
print(result)

#### Example 18: Array Broadcasting

In [124]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 0, -1])
result = matrix + vector
print(result)

[[2 2 2]
 [5 5 5]]


## Exercises

### Exercise 1: Array Creation
1. Create a 4x4 array filled with the value 7.
2. Generate an array of 10 random integers between 50 and 100.

### Exercise 2: Operations
1. Create two 3x3 arrays and compute their element-wise product.
2. Use `np.where()` to replace values less than 10 with 0 in an array.

### Exercise 3: Real-world Example
1. Simulate a temperature dataset (1D array of 7 days) with random values between 20 and 35. Calculate the average temperature.

# Exercise 1

In [3]:
arr=np.full((3,3),7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [6]:
arr1=np.arange(50,100)
arr1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Exercise 2


In [8]:
# 1. Create two 3x3 arrays and compute their element-wise product
array1 = np.random.randint(1, 10, size=(3, 3))
array2 = np.random.randint(1, 10, size=(3, 3))
elementwise_product = array1 * array2

print("\nArray 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Product:\n", elementwise_product)

# 2. Use np.where() to replace values less than 10 with 0 in an array
sample_array = np.array([5, 15, 2, 25, 10, 7])
modified_array = np.where(sample_array < 10, 0, sample_array)
print("\nOriginal Array:\n", sample_array)
print("Modified Array (values < 10 replaced with 0):\n", modified_array)



Array 1:
 [[8 3 7]
 [4 9 4]
 [2 7 6]]
Array 2:
 [[6 7 5]
 [1 6 6]
 [7 6 7]]
Element-wise Product:
 [[48 21 35]
 [ 4 54 24]
 [14 42 42]]

Original Array:
 [ 5 15  2 25 10  7]
Modified Array (values < 10 replaced with 0):
 [ 0 15  0 25 10  0]


# Exercise 3

In [9]:
# 1. Simulate temperature dataset for 7 days with values between 20 and 35
temperatures = np.random.uniform(20, 35, size=7)
average_temp = np.mean(temperatures)

print("\nTemperature readings for 7 days:\n", temperatures)
print("Average Temperature:", round(average_temp, 2), "°C")



Temperature readings for 7 days:
 [26.86976605 26.43928374 27.88238365 29.46412296 30.53320114 21.57323774
 33.58421577]
Average Temperature: 28.05 °C


# Task 
