# NumPy Exercises Notebook

Welcome to this Jupyter Notebook designed to help you master NumPy, a powerful library for numerical computing in Python.
This notebook contains exercises split into two levels: **Moderate** and **Advanced**.
These exercises build on foundational NumPy concepts such as array creation, basic operations, and indexing,
which you may already be familiar with from beginner-level material.
Here, we dive deeper into more complex operations and advanced techniques to test and enhance your skills.

In [1]:
import numpy as np

### Exercise 1: Reshape an Array
Create a 1D array with 12 elements using `np.arange()`, then reshape it into a 3x4 2D array.

In [5]:
# Your solution here
arr=np.arange(0,12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Exercise 2: Generate Random Numbers
Use `np.random.rand()` to create a 2x3 array filled with random numbers between 0 and 1.


In [8]:
# Your solution here
np.random.rand(3,4)

array([[0.18749183, 0.95554293, 0.16590205, 0.16519765],
       [0.76060116, 0.22139125, 0.93009777, 0.12414578],
       [0.35968007, 0.44354009, 0.82393056, 0.93058036]])

### Exercise 3: Find Max and Min
Given the array `arr = np.array([4, 2, 9, 1, 5])`, find its maximum and minimum values.


In [13]:
arr = np.array([4, 2, 9, 1, 5])
# Your solution here
print(arr.max())
print(arr.min())


9
1


### Exercise 4: Sum of Elements
Compute the total sum of all elements in the array `arr = np.array([[1, 2], [3, 4]])`.


In [16]:
arr = np.array([[1, 2], [3, 4]])
# Your solution here
np.sum(arr)

10

### Exercise 5: Boolean Indexing
Filter out all values greater than 5 from the array `arr = np.array([1, 6, 3, 8, 5])` using boolean indexing.


In [20]:
# Filter out all values greater than 5 from the array `arr = np.array([1, 6, 3, 8, 5])` using boolean indexing.

arr = np.array([1, 6, 3, 8, 5])
# Your solution here
print(arr>5)


[False  True False  True False]


### Exercise 6: Sum Along Axis
For the array `arr = np.array([[1, 2, 3], [4, 5, 6]])`, compute the sum along each column.


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Your solution here
print(arr.sum(axis=0))

[5 7 9]


### Exercise 7: Conditional Replacement
Use `np.where()` to replace all values less than 0 with 0 in the array `arr = np.array([-1, 2, -3, 4])`.


In [ ]:
arr = np.array([-1, 2, -3, 4])
# Your solution here
print(np.where(arr<0, 0, arr))


[0 2 0 4]


### Exercise 8: Concatenate Arrays
Concatenate the arrays `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])` horizontally (along columns).


In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Your solution here
np.concatenate((arr1, arr2), axis=0)


array([1, 2, 3, 4, 5, 6])

### Exercise 9: Split an Array
Split the array `arr = np.arange(10)` into two equal parts.


In [28]:

arr = np.arange(10)
# Your solution here
np.split(arr, 2)


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

### Exercise 10: Unique Elements
Find the unique elements in the array `arr = np.array([1, 2, 2, 3, 3, 3, 4])`.


In [30]:

arr = np.array([1, 2, 2, 3, 3, 3, 4])
# Your solution here
print(np.unique(arr))


[1 2 3 4]


### Exercise 11: Broadcasting
Add a 1D array `arr1 = np.array([1, 2, 3])` to a 2D array `arr2 = np.array([[4, 5, 6], [7, 8, 9]])` using broadcasting.


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
# Your solution here
print(arr1 + arr2)


[[ 5  7  9]
 [ 8 10 12]]


### Exercise 12: Views vs. Copies
Create a view of the array `arr = np.array([1, 2, 3, 4])`, modify the view, and print both the view and the original array to observe the effect.


In [55]:
arr = np.array([1, 2, 3, 4])
# Your solution here
arr_view = arr.view()
arr_view[0] = 10
print(arr_view)
print(arr)  # Original array is also modified


[10  2  3  4]
[10  2  3  4]


### Exercise 13: Increase Dimensions
Use `np.newaxis` to convert the 1D array `arr = np.array([1, 2, 3])` into a 2D array with shape (3, 1).


In [ ]:
arr = np.array([1, 2, 3])
# Your solution here
arr_2d = arr[:, np.newaxis]
print(arr_2d.shape)


(3, 1)


### Exercise 14: Structured Array

Create a structured array with fields `name` (string, max length 10), `age` (integer), and `height` (float). Add two entries: ("Alice", 25, 5.5) and ("Bob", 30, 6.0).


In [ ]:
# Your solution here
dtype = np.dtype([('name', 'S10'), ('age', 'i4'), ('height', 'f4')])
arr = np.zeros(2, dtype=dtype)
arr[0] = (b'Alice', 25, 5.5)
arr[1] = (b'Bob', 30, 6.0)
print(arr)




[(b'Alice', 25, 5.5) (b'Bob', 30, 6. )]


### Exercise 15: Custom Universal Function
Create a universal function (ufunc) that squares each element of an array. Apply it to `arr = np.array([1, 2, 3, 4])`.


In [43]:
arr = np.array([1, 2, 3, 4])
# Your solution here
squared = np.square(arr)
print(squared)



[ 1  4  9 16]


### Exercise 16: Vectorized Function
Use `np.vectorize()` to apply a function that checks if a number is even to each element of `arr = np.array([1, 2, 3, 4, 5])`.


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
# Your solution here
is_even = np.vectorize(lambda x: x % 2 == 0)
print(is_even(arr))



[False  True False  True False]


### Exercise 17: Memory Optimization
Create two arrays of 1000 integers: one using `np.int8` and one using `np.int64`. Compare their memory usage with `nbytes`.


In [47]:
# Your solution here
arr_int8 = np.arange(1000, dtype=np.int8)
arr_int64 = np.arange(1000, dtype=np.int64)
print(f"Memory usage of int8 array: {arr_int8.nbytes} bytes")
print(f"Memory usage of int64 array: {arr_int64.nbytes} bytes")


Memory usage of int8 array: 1000 bytes
Memory usage of int64 array: 8000 bytes


### Exercise 18: String Encoding/Decoding
Create an array of strings `["hello", "world"]`, encode them to bytes, and then decode them back to strings.


In [ ]:

arr = np.array(["hello", "world"])
# Your solution here
encoded = arr.astype('S')
decoded = encoded.astype(str)
print(encoded)
print(decoded)


[b'hello' b'world']
['hello' 'world']


### Exercise 19: Integer Array Indexing
Use integer array indexing to select elements at positions [1, 3, 4] from `arr = np.array([10, 20, 30, 40, 50])`.


In [51]:
arr = np.array([10, 20, 30, 40, 50])
# Your solution here
indices = np.array([1, 3, 4])
selected_elements = arr[indices]
print(selected_elements)


[20 40 50]


### Exercise 20: Mean Squared Error
Calculate the mean squared error (MSE) between `predictions = np.array([1.1, 2.0, 3.2])` and `labels = np.array([1.0, 2.0, 3.0])`.

$$
\text{mse} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y_i})^2
$$
where:

$n$: is the number of sample

$y_i$: are the acutal values and

$\hat{y_i}$: are the predicted values


In [53]:
predictions = np.array([1.1, 2.0, 3.2])
labels = np.array([1.0, 2.0, 3.0])
# Your solution here
mse = np.mean((predictions - labels) ** 2)
print(mse)


0.016666666666666694
